import { Toaster } from 'sonner';
import './globals.css';

export const metadata = {
	title: 'Storifal',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className="font-serif antialiased text-lightGray bg-black">
				<main className="relative flex flex-col items-center justify-items-center mx-auto">
					{children}
				</main>
				<Toaster />
			</body>
		</html>
	);
}
